services:
  fastapi:
    build: .
    container_name: agents_recruitment_core
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/app 
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8001 --reload
