services:
  postgres:
    image: postgres
    container_name: postgres-recruitment
    environment:
      POSTGRES_DB: recruitment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: recruitment
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./data:/var/lib/postgresql/data
